# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dbibinom_g <- function(N, y1, y2, xi, gamma) {
    .Call(`_twoCoprimary_dbibinom_g`, N, y1, y2, xi, gamma)
}

